<a href="https://colab.research.google.com/github/Mohamed-Khalil67/NLP/blob/main/Atelier_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [5]:
data_dir = '/content/drive/MyDrive/Colab Notebooks/movies.csv'

In [6]:
df = pd.read_csv(data_dir)

In [9]:
df.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [10]:
df.shape

(4803, 24)

In [19]:
def combined_features():
  df['features'] = df['keywords']+df['cast']+df['genres']+df['director']
  return df


In [30]:
data_frame = combined_features()

In [31]:
data_frame = data_frame.fillna(value='')

In [32]:
data_frame['features']

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6Dani...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799                                                     
4800    date love at first sight narration investigati...
4801                                                     
4802    obsession camcorder crush dream girlDrew Barry...
Name: features, Length: 4803, dtype: object

In [34]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data_frame['features'])
vectorizer.get_feature_names_out()

array(['11', '15th', '17th', ..., 'zwick', 'zwigoff', 'zylka'],
      dtype=object)

In [37]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
