<a href="https://colab.research.google.com/github/Mohamed-Khalil67/NLP/blob/main/Atelier_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [58]:
data_dir = '/content/drive/MyDrive/Colab Notebooks/movies.csv'

In [59]:
df = pd.read_csv(data_dir)

In [60]:
df.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [61]:
df.shape

(4803, 24)

In [62]:
def combined_features():
  df['features'] = df['keywords']+df['cast']+df['genres']+df['director']
  return df


In [63]:
data_frame = combined_features()

In [64]:
data_frame = data_frame.fillna(value='')

In [65]:
data_frame['features']

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6Dani...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799                                                     
4800    date love at first sight narration investigati...
4801                                                     
4802    obsession camcorder crush dream girlDrew Barry...
Name: features, Length: 4803, dtype: object

In [66]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data_frame['features'])
vectorizer.get_feature_names_out()

array(['11', '15th', '17th', ..., 'zwick', 'zwigoff', 'zylka'],
      dtype=object)

In [67]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [68]:
cosine_sim = cosine_similarity(X)


In [69]:
def get_title_from_index(index):
    return df[df.index == index]['title'].values[0]
def get_index_from_title(title):
    return df[df.title == title]['index'].values[0]

In [70]:
movie_user_likes = 'Titanic'
movie_index = get_index_from_title(movie_user_likes)
similar_movies = list(enumerate(cosine_sim[movie_index])) 

On affiche la liste des similarities et leur valeur au titre de titanic.

In [72]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:] # [1:] , skip the first one which is movie_user_like


In [77]:
i=0
print("Top 5 similar movies to " +movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar movies to Titanic are:

When Harry Met Sally...
Little Black Book
Blue Car
The Quick and the Dead
House of Sand and Fog
True Lies
